name: CI

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.platform.name }} ${{ matrix.config.name }}
    runs-on: ${{ matrix.platform.os }}

    strategy:
      matrix:
        platform:
        - { name: Windows VS2017, os: windows-2016   }
        - { name: Windows VS2019, os: windows-latest }
        - { name: Linux GCC,      os: ubuntu-latest  }
        - { name: Linux Clang,    os: ubuntu-latest, flags: -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ }
        - { name: MacOS XCode,    os: macos-latest   }
        config:
        - { name: Shared, flags: -DBUILD_SHARED_LIBS=TRUE }
        - { name: Static, flags: -DBUILD_SHARED_LIBS=FALSE }

        include:
        - platform: { name: MacOS XCode, os: macos-latest }
          config: { name: Frameworks, flags: -DSFML_BUILD_FRAMEWORKS=TRUE }
        - platform: { name: MacOS XCode, os: macos-latest }
          config: { name: iOS, flags: -DCMAKE_TOOLCHAIN_FILE=$GITHUB_WORKSPACE/cmake/toolchains/iOS.toolchain.cmake -DIOS_PLATFORM=SIMULATOR }

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Install Linux Dependencies
      if: runner.os == 'Linux'
      run: sudo apt-get install libxrandr-dev libxcursor-dev libudev-dev libopenal-dev libflac-dev libvorbis-dev libgl1-mesa-dev

    - name: Configure CMake
      shell: bash
      run: cmake -S $GITHUB_WORKSPACE -B $GITHUB_WORKSPACE/build ${{matrix.platform.flags}} ${{matrix.config.flags}} -DCMAKE_INSTALL_PREFIX=$GITHUB_WORKSPACE/install -DSFML_BUILD_EXAMPLES=TRUE -DCMAKE_VERBOSE_MAKEFILE=ON -DSFML_BUILD_TEST_SUITE=TRUE

    - name: Build
      shell: bash
      run: cmake --build $GITHUB_WORKSPACE/build --target install
